baseurl = "https://ros-tw.github.io"
title = "ROS Taiwan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

# [services]
# [services.disqus]
# shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "ROS Taiwan"
  info = "Robot Operating System (ROS) Taiwan Group"
  description = "Robot Operating System (ROS) Taiwan Group"
  keywords = "ros,robotics,taiwan"
  avatarurl = "images/avatar.png"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2018

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Discord"
  icon = "fa-brands fa-discord fa-2x"
  weight = 1
  url = "#"
[[params.social]]
  name = "Facebook"
  icon = "fa-brands fa-facebook fa-2x"
  weight = 2
  url = "https://www.facebook.com/groups/ros.taiwan"
# [[params.social]]
#   name = "Github"
#   icon = "fa-brands fa-github fa-2x"
#   weight = 3
#   url = "https://github.com/ros-tw/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Events"
  weight = 2
  url  = "events/"
[[menu.main]]
  name = "Contact"
  weight = 3
  url  = "contact/"
